source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'oj'
gem 'public_suffix'
gem 'addressable'
gem 'faraday'
gem 'faraday_middleware'

group :developemnt do
  gem 'pry'
end
