source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'oj'
gem 'public_suffix'
gem 'addressable'
gem 'faraday'
gem 'faraday_middleware'
gem 'faraday-http-cache'
gem 'dotenv'

group :production do
  gem 'redis'
  gem 'hiredis'
end

group :development, :test do
  gem 'pry'
  gem 'fakeredis'
end
