source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'oj'
gem 'public_suffix'
gem 'addressable'
gem 'faraday'
gem 'faraday_middleware'
gem 'redis'
gem 'hiredis'

group :development do
  gem 'pry'
end
